def build_text_report(schema, cleaning_report, model_info, insight, target):
    lines = []
    lines.append("CSV Insight Bot — Analysis Report")
    lines.append("--------------------------------")
    lines.append(f"Target column: {target}")
    lines.append("")
    lines.append("Schema Summary")
    lines.append(f"- Rows: {schema['rows']}")
    lines.append(f"- Columns: {schema['cols']}")
    lines.append(f"- Total missing cells (raw): {schema['total_missing_cells']}")
    lines.append("")
    lines.append("Cleaning Summary")
    lines.append(f"- Before: {cleaning_report['before_shape']['rows']} rows, {cleaning_report['before_shape']['cols']} cols")
    lines.append(f"- After:  {cleaning_report['after_shape']['rows']} rows, {cleaning_report['after_shape']['cols']} cols")
    lines.append(f"- Missing after cleaning: {cleaning_report['total_missing_after']}")
    lines.append("")
    lines.append("Model Summary")
    lines.append(f"- Problem type: {model_info['problem_type']}")
    lines.append(f"- Model used: {model_info['model_used']}")
    lines.append(f"- Metric: {model_info['metric']}")
    lines.append(f"- Score: {model_info['score']:.4f}")
    lines.append("")
    lines.append("Top Features")
    fi = model_info.get("feature_importance", [])
    if fi:
        for f, v in fi[:10]:
            lines.append(f"- {f}: {v:.4f}")
    else:
        lines.append("- (Not available)")
    lines.append("")
    lines.append("AI Insight")
    lines.append(insight.strip())
    lines.append("")
    return "\n".join(lines)